# Gopkg.toml for github.com/ulule/makroud

ignored = [
  "github.com/stretchr/testify/require",
  "github.com/davecgh/go-spew/spew",
  "github.com/go-xorm/core",
  "github.com/go-gorp/gorp",
  "github.com/go-xorm/xorm",
  "github.com/jinzhu/gorm",
  "github.com/jmoiron/sqlx"
]

[metadata]
  codename = "makroud"

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/ulule/sqlx"
  revision = "0bb2039bd75c1d5a044181b973c6323206281c0f"

[[constraint]]
  name = "github.com/ulule/sqalx"
  revision = "607b375fd15126a4528510d9512fb19eb050f448"

[[constraint]]
  name = "github.com/lib/pq"
  revision = "9eb73efc1fcc404148b56765b0d3f61d9a5ef8ee"

[[constraint]]
  name = "github.com/serenize/snaker"
  revision = "a683aaf2d516deecd70cad0c72e3ca773ecfcef0"

[[constraint]]
  name = "github.com/ulule/loukoum"
  revision = "e58f89d4b270c5c043f1852c27b319cfc68eaa06"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "v1.3.1"
