# Gopkg.toml for github.com/ulule/makroud

ignored = [
  "github.com/stretchr/testify/require",
  "github.com/davecgh/go-spew/spew",
  "github.com/go-xorm/core",
  "github.com/go-gorp/gorp",
  "github.com/go-xorm/xorm",
  "github.com/jinzhu/gorm",
  "github.com/jmoiron/sqlx"
]

[metadata]
  codename = "makroud"

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/ulule/sqlx"
  revision = "48295ab65cb8f057910839456253b2ad6a9e7f52"

[[constraint]]
  name = "github.com/ulule/sqalx"
  revision = "3768b124acdca09ede88e7e0f341a690cb650f05"

[[constraint]]
  name = "github.com/lib/pq"
  revision = "4ded0e9383f75c197b3a2aaa6d590ac52df6fd79"

[[constraint]]
  name = "github.com/serenize/snaker"
  revision = "a683aaf2d516deecd70cad0c72e3ca773ecfcef0"

[[constraint]]
  name = "github.com/ulule/loukoum"
  revision = "70542dabc493001df4c7aa1f8894a06e8934205a"

[[constraint]]
  name = "github.com/oklog/ulid"
  revision = "6276fb390df1e9be0f0721e1a7b0d6a8c973fa0c"
