version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init

      - run:
          name: Start docker container for postgres
          command: scripts/database --start

      - run:
          name: Run tests
          command: scripts/go-wrapper scripts/test
          no_output_timeout: 10m
          environment:
            DB_SETUP: false

      - run:
          name: Run linters
          command: scripts/go-wrapper scripts/lint
          no_output_timeout: 10m
